#!/bin/sh

# sudo mkdir -pv /var/{log,run}/gunicorn/ && sudo chown -cR ubuntu:ubuntu /var/{log,run}/gunicorn/

# Activate venv
. ~/tiktok_backend/env/bin/activate

# Stop gunicorn
sudo killall gunicorn > /dev/null 2>&1

sleep 3;

# Restart Nginx
sudo systemctl restart nginx

gunicorn -c ~/tiktok_backend/config/gunicorn/prod.py && echo "PROD Deployed!"
