# Generated by Django 4.1.11 on 2023-09-11 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tiktok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.TextField()),
                ('like_count', models.IntegerField()),
                ('view_count', models.IntegerField()),
                ('comment_count', models.IntegerField()),
                ('favourite_count', models.IntegerField()),
                ('improvement_like_count', models.IntegerField()),
                ('improvement_view_count', models.IntegerField()),
                ('improvement_comment_count', models.IntegerField()),
                ('improvement_favourite_count', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('url', models.TextField()),
                ('created', models.DateField()),
                ('last_updated', models.DateField(blank=True, null=True)),
                ('weekly_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiktok.weeklyreport')),
            ],
        ),
    ]
