# Generated by Django 2.2.12 on 2023-09-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tiktok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.TextField()),
                ('like_count', models.IntegerField()),
                ('view_count', models.IntegerField()),
                ('comment_count', models.IntegerField()),
                ('notes', models.TextField()),
                ('created', models.TimeField()),
            ],
        ),
    ]
