# Generated by Django 4.1.11 on 2024-02-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiktok',
            name='other_platform_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
