# Generated by Django 4.2.4 on 2023-09-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiktok',
            name='created',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tiktok',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
