# Generated by Django 4.1.11 on 2023-12-11 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyreport',
            name='platform',
            field=models.TextField(default='tiktok'),
            preserve_default=False,
        ),
    ]
