# Generated by Django 4.1.11 on 2023-09-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok', '0002_alter_weeklyreport_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyreport',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
