# Generated by Django 4.1.11 on 2024-03-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok', '0002_tiktok_other_platform_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyreport',
            name='created_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
