# Generated by Django 4.1.11 on 2023-12-11 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok', '0003_alter_weeklyreport_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.TextField(blank=True, null=True)),
                ('like_count', models.IntegerField()),
                ('view_count', models.IntegerField()),
                ('comment_count', models.IntegerField()),
                ('favourite_count', models.IntegerField()),
                ('share_count', models.IntegerField()),
                ('improvement_like_count', models.IntegerField()),
                ('improvement_view_count', models.IntegerField()),
                ('improvement_comment_count', models.IntegerField()),
                ('improvement_favourite_count', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('hook', models.TextField(blank=True, null=True)),
                ('improvements', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('created', models.DateField()),
                ('last_updated', models.DateField(blank=True, null=True)),
                ('order', models.IntegerField()),
                ('weekly_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiktok.weeklyreport')),
            ],
        ),
    ]
