# Generated by Django 4.1.11 on 2023-09-24 09:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok', '0003_alter_weeklyreport_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiktok',
            name='manual',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tiktok',
            name='thumbnail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tiktok',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
