# Generated by Django 4.2.4 on 2023-09-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok', '0004_remove_tiktok_weekly_report_id_tiktok_weekly_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyreport',
            name='total_comments',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='total_likes',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='total_views',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
