# Generated by Django 4.1.11 on 2023-09-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok', '0004_tiktok_manual_alter_tiktok_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiktok',
            name='manual',
            field=models.BooleanField(),
        ),
    ]
