# Generated by Django 4.2.4 on 2023-09-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok', '0005_weeklyreport_total_comments_weeklyreport_total_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiktok',
            name='favourite_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
