# Generated by Django 4.1.11 on 2023-09-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok', '0005_alter_tiktok_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiktok',
            name='manual',
            field=models.BooleanField(default=False),
        ),
    ]
