# Generated by Django 4.1.11 on 2023-09-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok', '0006_alter_tiktok_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiktok',
            name='hook',
            field=models.TextField(blank=True, null=True),
        ),
    ]
