# Generated by Django 4.1.11 on 2023-09-24 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok', '0007_tiktok_hook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyreport',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='weeklyreport',
            name='start_date',
        ),
    ]
