# Generated by Django 4.2.4 on 2023-09-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok', '0007_weeklyreport_total_favourites'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiktok',
            name='url',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
