# Generated by Django 4.2.4 on 2023-09-07 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok', '0008_tiktok_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyreport',
            name='total_comments',
        ),
        migrations.RemoveField(
            model_name='weeklyreport',
            name='total_favourites',
        ),
        migrations.RemoveField(
            model_name='weeklyreport',
            name='total_likes',
        ),
        migrations.RemoveField(
            model_name='weeklyreport',
            name='total_views',
        ),
    ]
