# Generated by Django 4.1.11 on 2023-10-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok', '0008_remove_weeklyreport_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiktok',
            name='improvements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
