# Generated by Django 4.2.4 on 2023-09-08 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok', '0009_remove_weeklyreport_total_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiktok',
            name='improvement_comment_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tiktok',
            name='improvement_favourite_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tiktok',
            name='improvement_like_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tiktok',
            name='improvement_view_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tiktok',
            name='last_updated',
            field=models.DateField(default='2023-09-08'),
            preserve_default=False,
        ),
    ]
