# Generated by Django 4.2.4 on 2023-09-08 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok', '0010_tiktok_improvement_comment_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiktok',
            name='last_updated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
