# Generated by Django 4.1.11 on 2023-10-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok', '0010_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiktok',
            name='share_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
