# Generated by Django 4.1.11 on 2023-10-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok', '0011_tiktok_share_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyreport',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
