name: Tests

on:
  push:
    branches:
      - main  # Change this to your main branch name
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Change this to your preferred Python version

    - name: Debug Environment
      run: env
    - name: Debug Secrets
      run: echo "Secrets= ${{ toJson(secrets) }}"
      
    - name: Set up Config JSON
      run: echo "${{ secrets.CONFIG }}" | sudo tee /etc/config.json
      
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          python -m playwright install

    - name: Run Pytest
      run: pytest
