name: Tests

on:
  push:
    branches:
      - main  # Change this to your main branch name
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    
    environment:
      name: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Change this to your preferred Python version
      
    - name: Set up Config JSON
      run: |
        cat <<EOF | sudo tee /etc/config.json
        ${CONFIG}
        EOF
      env:
        CONFIG: ${{ secrets.CONFIG }}
      
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          python -m playwright install

    - name: Run Pytest
      run: pytest
